import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.util.Hashtable;
import java.util.Random;

public class Main_Diabetes {
	public static void main(String[] args){
		Main_Base test = new Main_Base(		
			412,                              // Number of nodes in the graph
			89,                               // Target node for marginalization
			"diabetes.dsc",                   // Graph data file name
			"veInputDiabetes.txt",            // Cache file generated by the VE step (used by Gibbs sampling)
			"Diabetes_VE_1.txt",              // Accuracy trace file generated by the VE step
			"Diabetes_Leaky_2.txt",           // Accuracy trace file generated by Leaky joins
			"Diabetes_gibbs_2.txt",           // Accuracy trace file generated by Gibbs Sampling
			"Diabetes_CyclicSampling_2.txt",  // Accuracy trace file generated by Cyclic Sampling
			"Diabetes_RandomSampling_2.txt",  // Accuracy trace file generated by Random Sampling
			6000,                             // Sampling interval (in ms) -- Sampling processes emit samples once every period
			1800000                           // Cutoff interval (in ms) -- Abort sampling after this amount of time
		);
		
		//test.doVE();
		 test.doLeakyJoins();
		 test.doGibbsSampling();
		 test.doCyclicSampling();
		 test.doRandomSampling();
  }
}